import React from 'react';

interface AboutOverlayProps {
  isOpen: boolean;
  onClose: () => void;
}

const AboutOverlay: React.FC<AboutOverlayProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div 
      className="absolute inset-0 bg-slate-900/80 backdrop-blur-sm flex flex-col items-center justify-center p-4 z-30 animate-fade-in"
      onClick={onClose}
    >
      <div 
        className="bg-slate-800/80 p-8 rounded-xl shadow-2xl border border-slate-700 w-full max-w-2xl text-left relative"
        onClick={(e) => e.stopPropagation()}
      >
        <button 
          onClick={onClose}
          aria-label="Close about section"
          className="absolute top-4 right-4 text-slate-500 hover:text-cyan-300 transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
        
        <h2 className="text-3xl font-bold font-orbitron mb-6 text-yellow-300">About Typ-Affe</h2>
        
        <div className="space-y-4 text-slate-300 text-lg leading-relaxed">
          <p>
            <strong className="text-cyan-300">Typ-Affe</strong> is a sleek, modern web application designed to help you practice and improve your German typing skills in a focused, distraction-free environment.
          </p>
          <p>
            Heavily inspired by the popular typing test <a href="https://monkeytype.com/" target="_blank" rel="noopener noreferrer" className="text-yellow-300 underline hover:no-underline">Monkeytype</a>, this app offers a minimalist interface with a strong focus on performance and user experience.
          </p>
          <p>
            Key features include:
          </p>
          <ul className="list-disc list-inside space-y-2 pl-4">
            <li>
              <strong>Dynamic Content:</strong> Sentences are generated by Google's Gemini AI, tailored to specific <a href="https://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages" target="_blank" rel="noopener noreferrer" className="text-yellow-300 underline hover:no-underline">CEFR</a> language levels (A1-C2) for targeted practice.
            </li>
            <li>
              <strong>Customizable Tests:</strong> Choose your desired difficulty level and test duration, including an infinite practice mode.
            </li>
            <li>
              <strong>Real-time Feedback:</strong> Get instant WPM and accuracy stats, tracked and visualized in post-test charts.
            </li>
            <li>
              <strong>Translation Support:</strong> Toggle on-the-fly translations into several languages to aid your learning process.
            </li>
             <li>
              <strong>Pronunciation Aid:</strong> Hear the correct pronunciation for any word by hovering over it and clicking the speaker icon.
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default AboutOverlay;